import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import ThemeProvider from '@/components/theme-provider';
import ThemeSelector from '@/components/ThemeSelector';
import { Button } from '@/components/ui/button';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<ThemeProvider
					attribute='class'
					defaultTheme='system'
					enableSystem
					disableTransitionOnChange>
					<div className='m-4'>
						<nav className='flex justify-between'>
							<h1>Recipes for You</h1>
							<div>
								<Button>
									<Link href='/login'>Login</Link>
								</Button>
								<ThemeSelector />
							</div>
						</nav>
						{children}
					</div>
				</ThemeProvider>
			</body>
		</html>
	);
}
